### ISSUE TITLE
Open Source Licenses 101

### ISSUE THREAD

**Issue by firoze** [Mobiquity/teamstanton#12]
Introduce the world to the kinds of licenses that go into open source libraries, and how to interpret them when using said libraries in projects, and what that means for the project source code.

**Comment by gotoplanb** [comment]
Added milestone

**Comment by gotoplanb** [comment]
Stuff I'm going to read:

* [ ] http://www.cs.miami.edu/~burt/learning/Csc322.052/docs/opensourcedmk.pdf
* [ ] http://opensource.org/licenses/
* [ ] https://www.eff.org/search/site/licenses?f[0]=field_issue%3A526
