### ISSUE TITLE
Webview APIs in Android KITKAT

### ISSUE THREAD

**Issue by ashajgotra** [Mobiquity/teamstanton#35]

**Comment by gotoplanb** [comment]
Would be great to also discuss Lollipop and any differences between the various Android versions.

**Comment by ashajgotra** [comment]
Would do that!!

On Wed, Feb 11, 2015 at 6:34 PM, Dave Stanton <notifications@github.com>
wrote:

> Would be great to also discuss Lollipop and any differences between the
> various Android versions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mobiquity/teamstanton/issues/35#issuecomment-73988580>
> .
>



-- 
Ashutosh Shajgotra,Mobile Developer Mobile: 585-732-1601
237A SW 7th Terrace
Gainesville, FL 32601 Get the MobileDose
<http://www.mobiquityinc.com/our-ideas/get-dosed>Twitter
<https://twitter.com/mobiquityinc> | Facebook
<https://www.facebook.com/Mobiquity> | LinkedIn
<http://www.linkedin.com/company/mobiquity-inc.> | Skype [image: Mobiquity,
Inc.] <http://www.mobiquityinc.com/>

**Comment by gotoplanb** [comment]
Closed in #43
